"""
Django settings for pos_core project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iimkxxcz5p*io!okont^4z!yybcq7%=nu7+=d#to(4n$uqlylb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', # <-- AÑADE ESTA LÍNEA
    'tables',
    'dashboard',
    'inventory',
    'reports',
    'maestros',
    'core',
    'caja',
    'staff',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # --- AGREGA ESTO AL FINAL ---
    # Reemplaza 'pos_core' con el nombre de tu carpeta de proyecto si es diferente,
    # o simplemente usa 'core' si esa es tu app.
    'core.middleware.LoginRequiredMiddleware', 
]

ROOT_URLCONF = 'pos_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.configuracion_global',
            ],
        },
    },
]

WSGI_APPLICATION = 'pos_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- AÑADIR ESTO ---
# Le decimos a Django que busque archivos estáticos (CSS, JS, imágenes)
# en una carpeta llamada 'static' en la raíz del proyecto.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirección tras iniciar sesión (generalmente al Dashboard o Index)
LOGIN_REDIRECT_URL = 'panel_control' 

# Redirección tras cerrar sesión (vuelve al login)
LOGOUT_REDIRECT_URL = 'login' 

# URL de la página de login (para proteger las vistas)
LOGIN_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de Correo (Ejemplo con Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'frankdtg2004@gmail.com'  # <--- PON TU CORREO AQUÍ
EMAIL_HOST_PASSWORD = 'eryj fpwj gyat vpli'  # <--- TU CONTRASEÑA DE APLICACIÓN

# --- CONFIGURACIÓN DE TIMEOUT DE SESIÓN ---
# Cierra la sesión después de un tiempo de INACTIVIDAD.
# Para probar, lo ponemos en 60 segundos. Una vez que confirmes que funciona,
# puedes volver a ponerlo en 3600 (1 hora) o el tiempo que prefieras.
SESSION_COOKIE_AGE = 36000

# Al cerrar el navegador, la sesión expira inmediatamente.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Cada vez que el usuario hace una petición, el contador de inactividad se reinicia.
SESSION_SAVE_EVERY_REQUEST = True