# Generated by Django 5.2.9 on 2026-01-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Di Catia Pizzas', max_length=100)),
                ('rif', models.CharField(default='J-00000000-0', max_length=20, verbose_name='RIF / ID Fiscal')),
                ('direccion', models.TextField(blank=True, default='Caracas, Venezuela')),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('mensaje_ticket', models.CharField(default='¡Gracias por su compra!', help_text='Mensaje al final de la factura', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('tasa_dolar', models.DecimalField(decimal_places=2, default=40.0, max_digits=10, verbose_name='Tasa BCV ($)')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='% IVA')),
                ('igtf_porcentaje', models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='% IGTF (Divisas)')),
                ('servicio_porcentaje', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='% Servicio / Propina')),
                ('monto_delivery_fijo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Delivery Estándar ($)')),
                ('costo_caja_pequena', models.DecimalField(decimal_places=2, default=0.5, max_digits=10, verbose_name='Costo Caja Pequeña ($)')),
                ('costo_caja_grande', models.DecimalField(decimal_places=2, default=0.8, max_digits=10, verbose_name='Costo Caja Grande ($)')),
                ('gastos_operativos_porcentaje', models.DecimalField(decimal_places=2, default=10.0, help_text='% estimado de Luz, Gas, Alquiler por producto', max_digits=5, verbose_name='% Gastos Operativos')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
