# Generated by Django 5.2.9 on 2026-02-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='ancho_papel',
            field=models.IntegerField(default=80, help_text='Estándar: 80mm o 58mm', verbose_name='Ancho Papel (mm)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='auto_imprimir',
            field=models.BooleanField(default=True, help_text='Si se marca, el sistema intentará imprimir sin preguntar al cerrar la venta.', verbose_name='¿Impresión Automática?'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='impresora_ticket',
            field=models.CharField(blank=True, default='', help_text='Nombre de la impresora predeterminada en el sistema operativo', max_length=100, verbose_name='Nombre Impresora (Referencia)'),
        ),
    ]
