# Generated by Django 6.0.4 on 2026-05-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion_ancho_papel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='costo_caja_grande',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='costo_caja_pequena',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='gastos_operativos_porcentaje',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='igtf_porcentaje',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='monto_delivery_fijo',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='servicio_porcentaje',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='correo_destino_alertas',
            field=models.EmailField(blank=True, help_text='Correo donde llegará el PDF de insumos agotados.', max_length=254, null=True, verbose_name='Correo para alertas'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='enviar_alerta_stock_correo',
            field=models.BooleanField(default=False, verbose_name='¿Enviar alerta de stock por correo?'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='usar_scraping_bcv',
            field=models.BooleanField(default=True, help_text='Si se desactiva, el sistema utilizará la tasa manual ingresada arriba.', verbose_name='¿Actualizar Tasa BCV automáticamente?'),
        ),
    ]
