# Generated by Django 6.0.4 on 2026-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_configuracion_costo_caja_grande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='codigo_producto_automatico',
            field=models.BooleanField(default=True, help_text='Si está marcado, se generará un código autoincrementable. Si está desmarcado, podrás ingresarlo manualmente.', verbose_name='¿Código de producto automático?'),
        ),
    ]
