# Generated by Django 6.0.4 on 2026-05-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracion_codigo_producto_automatico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='iva_porcentaje',
        ),
    ]
