# Generated by Django 6.0.4 on 2026-05-19 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_configuracion_iva_porcentaje'),
        ('inventory', '0013_alter_insumo_es_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='caja_familiar',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_insumo_compuesto': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_caja_fam', to='inventory.insumo', verbose_name='Empaque Familiar'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='caja_individual',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_insumo_compuesto': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_caja_ind', to='inventory.insumo', verbose_name='Empaque Individual'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='caja_mediana',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_insumo_compuesto': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_caja_med', to='inventory.insumo', verbose_name='Empaque Mediano'),
        ),
    ]
