# Generated by Django 6.0.6 on 2026-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracion_caja_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='pm_banco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Banco Pago Móvil'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='pm_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula/RIF Pago Móvil'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='pm_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Pago Móvil'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='usar_logo_impresora',
            field=models.BooleanField(default=False, help_text='El logo debe estar pre-cargado en la memoria de la impresora térmica (NV Logo).', verbose_name='¿Imprimir logo en ticket?'),
        ),
    ]
