# Generated by Django 6.0.5 on 2026-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracion_pm_banco_configuracion_pm_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='abrir_caja_registradora',
            field=models.BooleanField(default=True, help_text='Si se marca, la impresora enviará el pulso para abrir la caja al generar la factura.', verbose_name='¿Abrir Gaveta de Dinero?'),
        ),
    ]
