# Generated by Django 6.0.6 on 2026-07-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracion_abrir_caja_registradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tasa_cashea',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Si es mayor a 0, esta será la tasa usada para calcular montos con Cashea. Si es 0, usará la tasa BCV general.', max_digits=10, verbose_name='Tasa Especial Cashea ($)'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='usar_tasa_bcv_para_cashea',
            field=models.BooleanField(default=True, help_text='Si está marcado, Cashea usará la tasa BCV automática. Si está desmarcado, usará la Tasa Especial Cashea que definas manualmente.', verbose_name='¿Cashea usa Tasa BCV?'),
        ),
    ]
