# Generated by Django 5.2.9 on 2025-12-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número de Mesa')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='¿Ocupada?')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
