# Generated by Django 5.2.9 on 2026-01-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tipo_servicio',
            field=models.CharField(choices=[('MESA', 'Comer en Mesa'), ('LLEVAR', 'Para Llevar'), ('DOMICILIO', 'Domicilio')], default='MESA', max_length=20, verbose_name='Tipo de Servicio'),
        ),
    ]
