# Generated by Django 5.2.9 on 2025-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_categoria_tasabcv_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('IND', 'Individual'), ('MED', 'Mediana'), ('FAM', 'Familiar'), ('UNI', 'Único/Bebida')], default='UNI', max_length=3, verbose_name='Tamaño'),
        ),
    ]
