# Generated by Django 5.2.9 on 2025-12-09 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_producto_tamano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
