# Generated by Django 5.2.9 on 2026-01-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_insumo_cantidad_porcion_extra_insumo_es_extra_and_more'),
        ('tables', '0003_venta_anulada_venta_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio cobrado por el extra', max_digits=10)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_elegidos', to='tables.detalleorden')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.insumo', verbose_name='Ingrediente Extra')),
            ],
        ),
    ]
