# Generated by Django 5.2.9 on 2025-12-11 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('tables', '0004_table_mesero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta ($)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('IND', 'Individual'), ('MED', 'Mediana'), ('FAM', 'Familiar'), ('UNI', 'Único/Bebida')], default='UNI', max_length=3),
        ),
        migrations.CreateModel(
            name='IngredienteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad a descontar del inventario (Ej: 0.200 para 200g)', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.insumo', verbose_name='Insumo (Inventario)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='tables.producto')),
            ],
        ),
    ]
