# Generated by Django 5.2.9 on 2026-01-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_detalleordenextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_extra', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='tables.detalleventa')),
            ],
        ),
    ]
