# Generated by Django 5.2.9 on 2026-01-28 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_insumo_cantidad_porcion_extra_insumo_es_extra_and_more'),
        ('tables', '0005_detalleventaextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(choices=[('IND', 'Individual'), ('MED', 'Mediana'), ('FAM', 'Familiar')], max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_extra', to='inventory.insumo')),
            ],
            options={
                'verbose_name': 'Precio de Extra',
                'verbose_name_plural': 'Precios de Extras',
                'unique_together': {('insumo', 'tamano')},
            },
        ),
    ]
