# Generated by Django 5.2.8 on 2025-12-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_remove_costoasignadoproducto_costo_adicional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FIJO', 'Monto Fijo ($)'), ('PORCENTAJE', '% del Costo de Receta')], default='FIJO', max_length=15)),
                ('valor_defecto', models.DecimalField(decimal_places=2, help_text='Ej: 0.50 para $0.50 o 10 para 10%', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('IND', 'Individual'), ('MED', 'Mediana'), ('FAM', 'Familiar'), ('UNI', 'Único/Bebida')], default='UNI', max_length=3, verbose_name='Tamaño'),
        ),
        migrations.CreateModel(
            name='CostoAsignadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, help_text='Valor específico para este producto', max_digits=10)),
                ('costo_adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.costoadicional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_adicionales', to='tables.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredienteProducto',
        ),
    ]
