# Generated by Django 5.2.9 on 2026-01-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_precioextra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precioextra',
            options={'verbose_name': 'Precio y Porción de Extra', 'verbose_name_plural': 'Precios y Porciones de Extras'},
        ),
        migrations.AddField(
            model_name='precioextra',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Peso de Porción'),
        ),
    ]
