# Generated by Django 6.0.4 on 2026-05-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_alter_precioextra_options_precioextra_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tasa_iva',
            field=models.DecimalField(choices=[('16.00', 'General (16%)'), ('8.00', 'Reducido (8%)'), ('31.00', 'Lujo (31%)'), ('0.00', 'Exento (0%)')], decimal_places=2, default='16.00', max_digits=5, verbose_name='Alícuota IVA'),
        ),
    ]
