# Generated by Django 6.0.4 on 2026-05-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_producto_tasa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Producto'),
        ),
    ]
