# Generated by Django 6.0.4 on 2026-05-09 18:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tasa_iva',
            field=models.DecimalField(choices=[(Decimal('16.00'), 'General (16%)'), (Decimal('8.00'), 'Reducido (8%)'), (Decimal('31.00'), 'Lujo (31%)'), (Decimal('0.00'), 'Exento (0%)')], decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='Alícuota IVA'),
        ),
    ]
