# Generated by Django 5.2.9 on 2025-12-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_producto_precio_alter_producto_tamano_and_more'),
        ('tables', '0009_table'),
    ]

    operations = [
    ]
