# Generated by Django 5.2.9 on 2025-12-15 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_merge_20251214_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FIJO', 'Monto Fijo ($)'), ('PORCENTAJE', '% del Costo de Receta')], default='FIJO', max_length=15)),
                ('valor_defecto', models.DecimalField(decimal_places=2, help_text='Ej: 0.50 para $0.50 o 10 para 10%', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CostoAsignadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, help_text='Valor específico para este producto', max_digits=10)),
                ('costo_adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.costoadicional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_adicionales', to='tables.producto')),
            ],
        ),
    ]
