# Generated by Django 6.0.4 on 2026-05-19 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_insumo_es_extra'),
        ('tables', '0010_alter_producto_tasa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='ingredientes_removidos',
            field=models.ManyToManyField(blank=True, to='inventory.insumo'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='mitad_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_como_mitad', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='ingredientes_removidos',
            field=models.ManyToManyField(blank=True, to='inventory.insumo'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='mitad_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitad_ventas', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_mitad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
