# Generated by Django 6.0.4 on 2026-05-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_detalleorden_ingredientes_removidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordenextra',
            name='porcion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='detalleventaextra',
            name='porcion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
