# Generated by Django 5.2.9 on 2025-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0011_costoadicional_costoasignadoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_materia_prima',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Ingredientes ($)'),
        ),
    ]
