# Generated by Django 6.0.5 on 2026-06-06 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_detalleordenextra_porcion_detalleventaextra_porcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='cuarto_2_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='cuarto_3_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='cuarto_4_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cuarto_2_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cuarto_3_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cuarto_4_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_cuarto_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_cuarto_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='nombre_cuarto_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
