# Generated by Django 6.0.5 on 2026-06-07 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_insumo_es_extra'),
        ('tables', '0013_detalleorden_cuarto_2_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenRemovido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcion', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removidos_detalles', to='tables.detalleorden')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaRemovido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('porcion', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removidos_detalles', to='tables.detalleventa')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.insumo')),
            ],
        ),
    ]
