# Generated by Django 5.2.9 on 2025-12-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_orden_detalleorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='solicitud_pago',
            field=models.BooleanField(default=False, verbose_name='¿Pidió Cuenta?'),
        ),
    ]
