# Generated by Django 6.0.6 on 2026-06-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_detalleordenremovido_detalleventaremovido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cuánto dinero entregó el cliente', max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='propina',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Monto excedente asignado a propina', max_digits=12),
        ),
    ]
