# Generated by Django 5.2.9 on 2025-12-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_table_solicitud_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuánto dinero entregó el cliente', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto excedente asignado a propina', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='mesa_numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta'), ('ZELLE', 'Zelle'), ('MIXTO', 'Mixto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Facturado'),
        ),
    ]
