# Generated by Django 6.0.6 on 2026-06-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_alter_pago_metodo_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='impreso',
            field=models.BooleanField(default=False, verbose_name='¿Ya impreso en comanda?'),
        ),
    ]
