# Generated by Django 5.2.9 on 2025-12-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_venta_monto_recibido_venta_propina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta'), ('ZELLE', 'Zelle')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto abonado en USD', max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Ref bancaria si aplica', max_length=50, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tables.venta')),
            ],
        ),
    ]
