# Generated by Django 5.2.9 on 2026-01-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_consumointerno'),
        ('tables', '0017_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='es_para_llevar',
            field=models.BooleanField(default=False, verbose_name='Para Llevar'),
        ),
        migrations.AddField(
            model_name='producto',
            name='insumo_empaque',
            field=models.ForeignKey(blank=True, help_text="Si se marca 'Para Llevar', se descontará 1 unidad de este insumo.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.insumo', verbose_name='Caja / Empaque'),
        ),
    ]
