# Generated by Django 6.0.6 on 2026-06-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_detalleorden_impreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta'), ('CASHEA', 'Cashea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta'), ('CASHEA', 'Cashea'), ('MIXTO', 'Mixto')], max_length=20),
        ),
    ]
