# Generated by Django 5.2.9 on 2026-01-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_consumointerno'),
        ('tables', '0018_detalleorden_es_para_llevar_producto_insumo_empaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='insumo_empaque',
            field=models.ForeignKey(blank=True, help_text='Caja que se descuenta si es para llevar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.insumo', verbose_name='Empaque / Caja'),
        ),
    ]
