# Generated by Django 6.0.6 on 2026-06-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0018_alter_pago_metodo_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta'), ('MIXTO', 'Mixto')], max_length=20),
        ),
    ]
