# Generated by Django 6.0.6 on 2026-06-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_alter_pago_metodo_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='color',
            field=models.CharField(default='#28a745', max_length=7, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área / Nombre'),
        ),
    ]
