# Generated by Django 6.0.6 on 2026-06-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0020_table_color_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='¿Es Externa?'),
        ),
    ]
