# Generated by Django 6.0.6 on 2026-06-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_table_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número de Mesa'),
        ),
    ]
