# Generated by Django 6.0.6 on 2026-07-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO_USD', 'Efectivo ($)'), ('EFECTIVO_BS', 'Efectivo (Bs)'), ('PAGO_MOVIL', 'Pago Móvil'), ('PUNTO', 'Punto de Venta'), ('CASHEA', 'Cashea')], max_length=20),
        ),
    ]
