# Generated by Django 6.0.6 on 2026-07-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tasa_aplicada',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa en el momento de la venta', max_digits=10, null=True),
        ),
    ]
