# Generated by Django 5.2.9 on 2025-12-10 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo ($)')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Stock Mínimo (Alerta)')),
                ('es_materia_prima', models.BooleanField(default=True, help_text='Marcar si se usa para cocinar (Harina). Desmarcar si es reventa (Refresco).')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categoriainsumo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Compra / Entrada'), ('SALIDA', 'Consumo / Merma'), ('AJUSTE', 'Ajuste de Inventario')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_unitario_movimiento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario ($)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, help_text='Ej: Compra en mercado, se cayó el frasco, etc.', max_length=255, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.insumo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
