# Generated by Django 5.2.8 on 2025-12-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='nota',
            field=models.CharField(blank=True, help_text='Ej: Compra en mercado, etc.', max_length=255, null=True),
        ),
    ]
