# Generated by Django 5.2.8 on 2025-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_movimientoinventario_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='es_insumo_compuesto',
            field=models.BooleanField(default=False, help_text='Activar si este insumo se prepara con otros insumos (Ej: Masa, Salsa Casera).', verbose_name='¿Es Insumo Compuesto?'),
        ),
    ]
