# Generated by Django 5.2.8 on 2025-12-16 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_insumo_es_insumo_compuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Cantidad necesaria para 1 unidad del padre', max_digits=10)),
                ('insumo_hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_compuestos', to='inventory.insumo')),
                ('insumo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='inventory.insumo')),
            ],
        ),
    ]
