# Generated by Django 5.2.8 on 2025-12-16 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ingredientecompuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='unidad_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unidadmedida', verbose_name='Unidad de Compra'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='1 para Gramos/ML. 1000 para KG/L.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientecompuesto',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Costo x Gramo ($)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='es_insumo_compuesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='es_materia_prima',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=500, max_digits=12),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unidadmedida', verbose_name='Unidad Base (Almacén)'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad Comprada'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='costo_unitario_movimiento',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Costo por Unidad de Compra'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='nota',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Compra'), ('SALIDA', 'Consumo'), ('AJUSTE', 'Ajuste')], max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
