# Generated by Django 5.2.8 on 2025-12-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_movimientoinventario_unidad_movimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='es_materia_prima',
        ),
        migrations.AddField(
            model_name='insumo',
            name='merma_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Merma'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_mercado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Mercado ($)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Costo Real x Gramo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unidadmedida', verbose_name='Unidad Base'),
        ),
    ]
