# Generated by Django 5.2.8 on 2025-12-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_insumo_es_materia_prima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_por_precio',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Ej: 1000 si el precio es por Kilo. 1 si es por unidad.', max_digits=10, verbose_name='Cant. por Precio'),
        ),
    ]
