# Generated by Django 5.2.9 on 2025-12-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_insumo_cantidad_por_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientecompuesto',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad necesaria para fabricar 1 unidad del padre', max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad_por_precio',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Cant. Ref'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='costo_unitario_movimiento',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Compra/Prod'), ('SALIDA', 'Consumo/Merma'), ('AJUSTE', 'Ajuste')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='unidad_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unidadmedida'),
        ),
    ]
