# Generated by Django 5.2.9 on 2026-01-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_consumointerno'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='rendimiento',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Rendimiento (Cantidad Final Producida)'),
        ),
    ]
