# Generated by Django 5.2.9 on 2026-01-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_insumo_rendimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_por_precio',
        ),
        migrations.AddField(
            model_name='insumo',
            name='peso_standar',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Peso por Unidad de Compra (Gr/Ml)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_mercado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de la Unidad ($)'),
        ),
    ]
