# Generated by Django 5.2.9 on 2026-01-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_insumo_cantidad_por_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_porcion_extra',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Cantidad a descontar por cada extra vendido (Ej: 0.050 para 50g)', max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='es_extra',
            field=models.BooleanField(default=False, verbose_name='¿Se vende como Extra?'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_venta_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta Extra ($)'),
        ),
    ]
