# Generated by Django 5.2.9 on 2026-01-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_insumo_cantidad_porcion_extra_insumo_es_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='es_extra',
            field=models.BooleanField(default=False, help_text='Marca esta casilla si este ingrediente puede ser agregado como extra en un producto.', verbose_name='¿Se vende como Extra?'),
        ),
    ]
