# Generated by Django 5.2.9 on 2025-12-18 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mesa_numero', models.IntegerField()),
                ('mesero_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('resumen_pedido', models.TextField(help_text='Lista de productos que tenía la mesa')),
                ('total_eliminado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de eliminación')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Quién eliminó')),
            ],
        ),
    ]
