# Generated by Django 6.0.5 on 2026-06-14 00:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auditoriaconfiguracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha_cuadre', models.DateField(default=django.utils.timezone.now)),
                ('sistema_efectivo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fisico_efectivo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sistema_efectivo_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fisico_efectivo_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sistema_electronico_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fisico_electronico_bs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sistema_electronico_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fisico_electronico_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
