# Generated by Django 6.0.6 on 2026-06-30 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_cuadrecaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaconfiguracion',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='auditoriaconfiguracion',
            name='detalles',
        ),
        migrations.AddField(
            model_name='auditoriaconfiguracion',
            name='seccion',
            field=models.CharField(blank=True, help_text='Ej: Identidad, Economía, Visual', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditoriaconfiguracion',
            name='accion',
            field=models.CharField(help_text='Descripción del cambio realizado', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditoriaconfiguracion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CuadreCaja',
        ),
    ]
