# Generated by Django 6.0.6 on 2026-07-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_auditoriaconfiguracion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaconfiguracion',
            name='accion_detalle',
            field=models.CharField(blank=True, help_text='Detalles específicos del cambio, como valores antiguos y nuevos.', max_length=500, null=True),
        ),
    ]
