# Generated by Django 6.0.6 on 2026-06-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrecaja',
            name='fondo_inicial_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fondo Inicial USD'),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='total_gastos_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Gastos USD'),
        ),
    ]
