# Generated by Django 6.0.6 on 2026-07-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cuadrecaja_fondo_inicial_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='fisico_efectivo_bs',
            new_name='recibido_efectivo_bs',
        ),
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='fisico_efectivo_usd',
            new_name='recibido_efectivo_usd',
        ),
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='fisico_electronico_bs',
            new_name='recibido_electronico_bs',
        ),
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='fisico_electronico_usd',
            new_name='recibido_electronico_usd',
        ),
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='sistema_efectivo_bs',
            new_name='total_esperado_usd',
        ),
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='sistema_efectivo_usd',
            new_name='total_recibido_usd',
        ),
        migrations.RenameField(
            model_name='cuadrecaja',
            old_name='sistema_electronico_bs',
            new_name='total_ventas_dia',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='fondo_inicial_usd',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='sistema_electronico_usd',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='total_gastos_usd',
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='diferencia_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Positivo si sobra, negativo si falta', max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='fondo_caja_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fondo de Caja USD'),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='gastos_turno_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos del Turno USD'),
        ),
    ]
