# Generated by Django 6.0.6 on 2026-07-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_rename_fisico_efectivo_bs_cuadrecaja_recibido_efectivo_bs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='gastos_turno_usd',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='recibido_efectivo_bs',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='recibido_efectivo_usd',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='recibido_electronico_bs',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='recibido_electronico_usd',
        ),
        migrations.RemoveField(
            model_name='cuadrecaja',
            name='total_ventas_dia',
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='cashea_financiado_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='cashea_recibido_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='dolares_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='efectivo_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='gastos_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='gastos_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='pago_movil_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='punto_venta_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='tasa_cashea',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='tasa_general',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='total_ventas_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='ventas_sistema_cashea',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total ventas por Cashea', max_digits=12),
        ),
        migrations.AddField(
            model_name='cuadrecaja',
            name='ventas_sistema_general',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total ventas sin Cashea', max_digits=12),
        ),
    ]
