# Generated by Django 6.0.6 on 2026-07-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_remove_cuadrecaja_gastos_turno_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrecaja',
            name='total_propinas_sistema',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total propinas registradas', max_digits=12),
        ),
    ]
